#ifndef ELYSIAN_RENDERER_VULKAN_HPP
#define ELYSIAN_RENDERER_VULKAN_HPP

#include <vulkan/vulkan.hpp>

// INITIAL VALUES FROM ENV OR BUID FLAGS
//MVK_DEBUG - enable debug mode by default
//MVK_CONFIG_SHADER_CONVERSION_FLIP_VERTEX_Y
//MVK_CONFIG_SYNCHRONOUS_QUEUE_SUBMITS
//VK_CONFIG_PREFILL_METAL_COMMAND_BUFFERS
//MVK_CONFIG_MAX_ACTIVE_METAL_COMMAND_BUFFERS_PER_QUEUE
//MVK_CONFIG_SUPPORT_LARGE_QUERY_POOLS
//MVK_CONFIG_SWAPCHAIN_MAG_FILTER_USE_NEAREST
//MVK_CONFIG_METAL_COMPILE_TIMEOUT
//MVK_CONFIG_PERFORMANCE_TRACKING
//MVK_CONFIG_PERFORMANCE_LOGGING_FRAME_COUNT
//MVK_CONFIG_DISPLAY_WATERMARK
//MVK_CONFIG_SPECIALIZED_QUEUE_FAMILIES
//MVK_CONFIG_SWITCH_SYSTEM_GPU
//MVK_CONFIG_FULL_IMAGE_VIEW_SWIZZLE
//MVK_CONFIG_DEFAULT_GPU_CAPTURE_SCOPE_QUEUE_FAMILY_INDEX
//MVK_CONFIG_DEFAULT_GPU_CAPTURE_SCOPE_QUEUE_INDEX
#include <MoltenVk/vk_mvk_moltenvk.h>

#endif // ELYSIAN_RENDERER_VULKAN_HPP
